### PR TITLE
fixing some bugs

### PR DESCRIPTION
**Pull request by Sergemuhundu**
#819

### CODE REVIEW

**Comment by evereq** [comment]
@Sergemuhundu merge issues, also can you make small PRs please? This one chanig so many files, its hard go see what. Maybe you forgot to rebase or?

**Comment by Sergemuhundu** [comment]
> @Sergemuhundu merge issues, also can you make small PRs please? This one chanig so many files, its hard go see what. Maybe you forgot to rebase or?

Yes @evereq  i forgot to rebase. Let me handle it

**Comment by Sergemuhundu** [comment]
@evereq  conflicts resolved.

**Comment by Sergemuhundu** [comment]
@evereq  conflicts resolved.

**Pull request merged**
